[providers]
node = '18'

[phases.setup]
nixPkgs = ['pnpm']

[phases.build]
cmds = [
  'cd ../..',
  'pnpm install --no-frozen-lockfile',
  'pnpm --filter web build'
]

[start]
cmd = 'cd ../../apps/web && npx serve dist -s -p $PORT'

[variables]
NODE_ENV = 'production'
