providers = ['node']

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = [
  'cp package.simple.json package.json',
  'cp tsconfig.simple.json tsconfig.app.json',
  'cp vite.simple.config.ts vite.config.ts',
  'cp postcss.simple.config.js postcss.config.js',
  'cp index.simple.html index.html',
  'npm install',
  'npm run build'
]

[start]
cmd = 'serve dist -s -p $PORT'
