# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"  # Frontend dev server
      - "3001:3001"  # Backend server
      - "80:80"      # Production nginx
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=5173
      - BACKEND_PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/server/node_modules
    command: pnpm dev
    profiles:
      - dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  production:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod
    command: ["sh", "-c", "nginx && node backend/dist/index.js"]
