[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "cd apps/server && node dist/index.js"

[[deploy.environmentVariables]]
name = "NODE_ENV" 
value = "production"
